### ISSUE TITLE
What is the evaluation code bug?

### ISSUE THREAD

**Issue by wjn922** [ksaito-ut/openworld_ldet#4] opened 2022-03-10 07:33 UTC
Hi,

I notice that you update the README and said there is an evaluation code bug. Could you plz give more information about this?

**Comment by ksaito-ut** [comment] 2022-03-11 20:27
Hi, I have updated the evaluation code. The pascal_ids were not indexed correctly. The problem is fixed now. But, we made another little update in the evaluation protocol in our new paper. So, we will further update the evaluation part soon.

**Comment by wjn922** [comment] 2022-03-12 03:29
Well, that would be a problem. Then I suppose the performance would be reduced. Could you plz share the updated paper?Many thanks.

**Comment by ksaito-ut** [comment] 2022-04-12 01:05
Hi, sorry for the late reply. We have uploaded paper and available at https://github.com/ksaito-ut/openworld_ldet/blob/main/docs/paper.pdf.

**Comment by wjn922** [comment] 2022-04-12 02:46
Thanks.

**Comment by wjn922** [comment] 2022-04-12 07:23
Hi, 

I run your evaluation code and found that there are two metrics. For example, in the figure below (voc->non-voc setting), the AR of `classwise` is slightly higher than the previous one. Could you please help me tell the differences? Thanks!
![image](https://user-images.githubusercontent.com/21001460/162903653-8d6b2bd3-20ec-4907-99df-df045df0e7ed.png)

**Comment by wjn922** [comment] 2022-04-12 08:03
By the way, I also wonder how to evaluate the ALL metrics shown in Table 1 and Table 8?

**Comment by wjn922** [comment] 2022-04-12 12:44
It seems that `eval_obj365' is not used by the evaluation code. Would you please check this part? https://github.com/ksaito-ut/openworld_ldet/blob/0e5a991eb169779940ec24fd04ef3af6b9c14b5f/ldet/evaluation/coco_evaluation.py#L175

**Closed as completed** 2022-04-18 07:21 UTC
